In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('PCA3.xlsx', index_col=0)
data = data.values
data[data == 0] = -1
data

array([[-1,  1,  1, ...,  1,  1,  1],
       [-1, -1, -1, ...,  1,  1,  1],
       [ 1,  1,  1, ..., -1, -1, -1],
       ...,
       [-1, -1,  1, ..., -1, -1, -1],
       [ 1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [3]:
S = data
ST = np.transpose(data)
score = [0.65636, 0.65858, 0.66430, 0.67855, 0.83352, 0.83116, 0.83619, 0.83961, 0.84461]
#score = [0.83352, 0.83116, 0.83619, 0.83961, 0.84461]
K = 120000

In [4]:
type(score)

list

In [8]:
STy = []
for num in score:
    a = num * K * 2 - K
    STy.append(a)
STy = np.array(STy)
STy = STy.T
STy

array([37526.4, 38059.2, 39432. , 42852. , 80044.8, 79478.4, 80685.6,
       81506.4, 82706.4])

In [6]:
b = np.dot(ST, S)
b = np.linalg.inv(b)
weight = np.dot(b.T, STy)
weight

array([ 0.07974882,  0.07339118,  0.08020743,  0.09791108, -0.11486349,
       -0.0689492 ,  0.11262124, -0.01662122,  0.68277759])

matrix([[ 0.07974882],
        [ 0.07339118],
        [ 0.08020743],
        [ 0.09791108],
        [-0.11486349],
        [-0.0689492 ],
        [ 0.11262124],
        [-0.01662122],
        [ 0.68277759]])

In [ ]:
#array([ 0.07974882,  0.07339118,  0.08020743,  0.09791108, -0.11486349, -0.0689492 ,  0.11262124, -0.01662122,  0.68277759])

In [22]:
sum1 = 0
for i in range(len(weight)):
    sum1 = weight[i] + sum1
sum1

1.1386422061563395

In [16]:
###后来加上的
#S[S == -1] = 0
#S

array([[0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
result = np.dot(S, weight.T)

In [24]:
result = result.tolist()

In [25]:
result = pd.DataFrame(result)

In [27]:
result.to_csv('Result6(PCA3).csv',encoding='gbk')